### Create a new task
POST http://localhost:8080/users/sign-up
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

### Login, should return an authorization token
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}